#!/bin/bash
#This script will generate outputs of unique snv locations of golden set, monovar and bcftools in the text format 
#This needs following input files:
#a) all single cell and all bulk vcf generated by bcftools (in the tool output directory)
#b) true_mutations_all_proto.csv (in the tool output directory)
#c) all_bulk.vcf and all_sc.vcf generated by monovar (in the tool output directory)

cat ${1}bulk*.vcf ${1}sc*.vcf |grep -v "#"|cut -f2|sort |uniq > ${1}bcftools.txt
cat ${3}true_mutations_all_proto.csv|tr ',' '\t'|awk 'NR>1 {if ($3==1) print $2 }'|sed  '/^$/d' |sort|uniq  > ${3}golden.txt
cat ${2}all_bulk.vcf ${2}all_sc.vcf |grep -v "#"|cut -f2|sort |uniq > ${2}monovar.txt
